[workspace]
members = ["core"]
resolver = "2"

[workspace.package]
version = "0.3.2"
edition = "2021"
rust-version = "1.80"
license = "MIT"

[package]
name = "trayci"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png", "tray-icon"] }
tauri-plugin-notification = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-global-shortcut = "2"
tokio = { version = "1", features = ["fs", "io-util", "sync"] }
trayci-core = { path = "core" }
